version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: "./Dockerfile"
    working_dir: /var/www/
    container_name: geolocation-finder-app    
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "8000:5173"
    networks:
      - geolocation-finder-network
    volumes:
      - ./:/var/www/
networks:
  geolocation-finder-network:
    driver: bridge
